Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
Creation-Date: 2019-07-29T13:10:53+10:00

====== Dockerfile ======
Created Monday 29 July 2019

Barefoot uses a docker container to import osm data into its own psql database. As of late July 2019 the building of this container failed until I change the osmosis version being installed from 0.43.1 to 0.44.1.
